# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e7a52376a5ec80af4ce0d5eb1bced114"
name = "futureblink-announcement-app"
application_url = "https://futureblink-shopify-app-assignment.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://futureblink-shopify-app-assignment.onrender.com/auth/callback",
  "https://futureblink-shopify-app-assignment.onrender.com/auth/shopify/callback",
  "https://futureblink-shopify-app-assignment.onrender.com/api/auth"
]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
